### ISSUE TITLE
basic example fails with "Required parameter is missing: grant_type"

### ISSUE THREAD

**Issue by aep** [abronte/BigQuery#21]
the very first example code in the readme fails for me with:

/home/aep/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:947:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error" : "invalid_request",
  "error_description" : "Required parameter is missing: grant_type"
}
	from /home/aep/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:964:in `fetch_access_token!'
	from /home/aep/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bigquery-0.7.0/lib/big_query/client.rb:42:in `refresh_auth'
	from /home/aep/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bigquery-0.7.0/lib/big_query/client.rb:33:in `initialize'
	from main.rb:13:in `new'
	from main.rb:13:in `<main>'

**Comment by gambaroff** [comment]
Could paste the code making a request? There is an error in your request.

**Comment by trinityXmontoya** [comment]
"If you're getting an "invalid_grant" error it usually means your system clock is off."

```
	def self.initialize
		opts = {}
		opts['client_id']     = ENV["GOOGLE_BQ_CLIENT_ID"]
		opts['service_email'] = ENV["GOOGLE_BQ_EMAIL_ADDRESS"]
		opts['key']           = './my-secret-key.p12'
		opts['project_id']    = ENV["GOOGLE_BQ_PROJECT_ID"]
		opts['dataset']       = '[gdelt-bq:full.events]'

		bq = BigQuery::Client.new(opts)
	end
```
^ that is my sample query, and the error I get when trying to connect is 

```
Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error" : "invalid_grant"
}
from /Users/MY_ACCT/.rvm/gems/ruby-2.1.5/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:966:in `fetch_access_token
'
```

I checked and my system clock is correct, wondering if there are other possible reasons this error could be happening?

**Comment by trinityXmontoya** [comment]
I was having the same issue and followed the steps exactly as given in the readme. I also checked to make sure that my computer clock was correct and that the secret key is valid and authorized the provided client_id within the scope of the big_query api.

```
		opts = {}
		opts['client_id']     = ENV["GOOGLE_BQ_CLIENT_ID"]
		opts['service_email'] = ENV["GOOGLE_BQ_SERVICE_EMAIL"]
		opts['key']           = './my-secret-key.p12'
		opts['project_id']    = ENV["GOOGLE_BQ_PROJECT_ID"]
		opts['dataset']       = 'gdelt-bq:full.events'

		bq = BigQuery::Client.new(opts)
```
